export const GITA_DATA = [
  { "chapter_number": 2, "verse_number": 14, "sloka": "मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः | आगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत ||2-14||", "transliteration": "mātrāsparśāstu kaunteya śītoṣṇasukhaduḥkhadāḥ | āgamāpāyino'nityāstāṁstitikṣasva bhārata ||2-14||", "meaning": "O son of Kunti, the nonpermanent appearance of happiness and distress, and their disappearance in due course, are like the appearance and disappearance of winter and summer seasons. They arise from sense perception, O scion of Bharata, and one must learn to tolerate them without being disturbed." },
  { "chapter_number": 2, "verse_number": 47, "sloka": "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन | मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ||2-47||", "transliteration": "karmaṇyevādhikāraste mā phaleṣu kadācana | mā karmaphalaheturbhūrmā te saṅgo'stvakarmaṇi", "meaning": "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Never consider yourself the cause of the results of your activities, and never be attached to not doing your duty." },
  { "chapter_number": 2, "verse_number": 48, "sloka": "योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय | सिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते ||2-48||", "transliteration": "yogasthaḥ kuru karmāṇi saṅgaṁ tyaktvā dhanañjaya | siddhyasiddhyoḥ samo bhūtvā samatvaṁ yoga ucyate ||2-48||", "meaning": "Perform your duty equipoised, O Arjuna, abandoning all attachment to success or failure. Such equanimity is called yoga." },
  { "chapter_number": 3, "verse_number": 5, "sloka": "न हि कश्चित्क्षणमपि जातु तिष्ठत्यकर्मकृत् | कार्यते ह्यवशः कर्म सर्वः प्रकृतिजैर्गुणैः ||3-5||", "transliteration": "na hi kaścitkṣaṇamapi jātu tiṣṭhatyakarmakṛt | kāryate hyavaśaḥ karma sarvaḥ prakṛtijairguṇaiḥ ||3-5||", "meaning": "Everyone is forced to act helplessly according to the qualities he has acquired from the modes of material nature; therefore no one can refrain from doing something, not even for a moment." },
  { "chapter_number": 9, "verse_number": 26, "sloka": "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति | तदहं भक्त्युपहृतमश्नामि प्रयतात्मनः ||9-26||", "transliteration": "patraṁ puṣpaṁ phalaṁ toyaṁ yo me bhaktyā prayacchati | tadahaṁ bhaktyupahṛtamaśnāmi prayatātmanaḥ ||9-26||", "meaning": "If one offers Me with love and devotion a leaf, a flower, a fruit or water, I will accept it." },
  { "chapter_number": 12, "verse_number": 13, "sloka": "अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च | निर्ममो निरहङ्कारः समदुःखसुखः क्षमी ||12-13||", "transliteration": "adveṣṭā sarvabhūtānāṁ maitraḥ karuṇa eva ca | nirmamo nirahaṅkāraḥ samaduḥkhasukhaḥ kṣamī ||12-13||", "meaning": "One who is not envious but is a kind friend to all living entities, who does not think himself a proprietor and is free from false ego, who is equal in both happiness and distress, who is tolerant... such a devotee of Mine is very dear to Me." },
  { "chapter_number": 18, "verse_number": 66, "sloka": "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज | अहं त्वा सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः ||18-66||", "transliteration": "sarvadharmānparityajya māmekaṁ śaraṇaṁ vraja | ahaṁ tvā sarvapāpebhyo mokṣayiṣyāmi mā śucaḥ", "meaning": "Abandon all varieties of religion and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear." }
];
